//! Constant-folding pass (AT-7).
//!
//! Evaluates integer arithmetic on `ConstI32`/`ConstI64` operands and replaces
//! the consuming op with a new constant.  Handles the common ALU ops that
//! appear in ARM64 code generated by Clang: Add/Sub/And/Or/Xor/Shl/LShr/AShr.

use alloc::collections::BTreeMap;
use alloc::vec::Vec;

use crate::ir::{IrFunction, IrOp};

pub struct ConstFoldPass;

impl ConstFoldPass {
    pub fn run(mut func: IrFunction) -> IrFunction {
        for blk in &mut func.blocks {
            // Map: IrValueId → i64 constant (only for ConstI32/ConstI64 ops).
            let mut consts: BTreeMap<u32, i64> = BTreeMap::new();
            let mut new_ops: Vec<IrOp> = Vec::with_capacity(blk.ops.len());

            for op in blk.ops.drain(..) {
                match op {
                    IrOp::ConstI32 { dst, val } => {
                        consts.insert(dst.0, val as i64);
                        new_ops.push(IrOp::ConstI32 { dst, val });
                    }
                    IrOp::ConstI64 { dst, val } => {
                        consts.insert(dst.0, val);
                        new_ops.push(IrOp::ConstI64 { dst, val });
                    }
                    IrOp::Add { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let v = ca.wrapping_add(cb);
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Add { dst, a, b });
                        }
                    }
                    IrOp::Sub { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let v = ca.wrapping_sub(cb);
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Sub { dst, a, b });
                        }
                    }
                    IrOp::And { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let v = ca & cb;
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::And { dst, a, b });
                        }
                    }
                    IrOp::Or { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let v = ca | cb;
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Or { dst, a, b });
                        }
                    }
                    IrOp::Xor { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let v = ca ^ cb;
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Xor { dst, a, b });
                        }
                    }
                    IrOp::Shl { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let shift = (cb & 63) as u32;
                            let v = (ca as u64).wrapping_shl(shift) as i64;
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Shl { dst, a, b });
                        }
                    }
                    IrOp::LShr { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let shift = (cb & 63) as u32;
                            let v = (ca as u64).wrapping_shr(shift) as i64;
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::LShr { dst, a, b });
                        }
                    }
                    IrOp::AShr { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let shift = (cb & 63) as u32;
                            let v = ca.wrapping_shr(shift);
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::AShr { dst, a, b });
                        }
                    }
                    IrOp::Mul { dst, a, b } => {
                        if let (Some(&ca), Some(&cb)) = (consts.get(&a.0), consts.get(&b.0)) {
                            let v = ca.wrapping_mul(cb);
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Mul { dst, a, b });
                        }
                    }
                    IrOp::Neg { dst, a } => {
                        if let Some(&ca) = consts.get(&a.0) {
                            let v = ca.wrapping_neg();
                            consts.insert(dst.0, v);
                            new_ops.push(IrOp::ConstI64 { dst, val: v });
                        } else {
                            new_ops.push(IrOp::Neg { dst, a });
                        }
                    }
                    other => new_ops.push(other),
                }
            }

            blk.ops = new_ops;
        }
        func
    }
}
